/// <autosync enabled="true" />
/// <reference path="../content/igra1 (web)/data/isplayer.js" />
/// <reference path="../content/igra1 (web)/data/player.js" />
/// <reference path="../content/igra1 (web)/data/slide1.js" />
/// <reference path="../content/igra1 (web)/data/slide2.js" />
/// <reference path="../content/igra1 (web)/data/slide3.js" />
/// <reference path="../content/igra1 (web)/data/slide4.js" />
/// <reference path="../content/igra1 (web)/data/slide5.js" />
/// <reference path="../content/igra2 (web)/data/isplayer.js" />
/// <reference path="../content/igra2 (web)/data/player.js" />
/// <reference path="../content/igra2 (web)/data/slide1.js" />
/// <reference path="../content/igra2 (web)/data/slide2.js" />
/// <reference path="../content/igra2 (web)/data/slide3.js" />
/// <reference path="../content/igra2 (web)/data/slide4.js" />
/// <reference path="../content/igra2 (web)/data/slide5.js" />
/// <reference path="../content/igra3 (web)/data/isplayer.js" />
/// <reference path="../content/igra3 (web)/data/player.js" />
/// <reference path="../content/igra3 (web)/data/slide1.js" />
/// <reference path="../content/igra3 (web)/data/slide2.js" />
/// <reference path="../content/igra3 (web)/data/slide3.js" />
/// <reference path="../content/igra6 (web)/data/isplayer.js" />
/// <reference path="../content/igra6 (web)/data/player.js" />
/// <reference path="../content/igra6 (web)/data/slide1.js" />
/// <reference path="../content/igra6 (web)/data/slide2.js" />
/// <reference path="../content/igra6 (web)/data/slide3.js" />
/// <reference path="../content/igra6 (web)/data/slide4.js" />
/// <reference path="../content/igra6 (web)/data/slide5.js" />
/// <reference path="ai.0.22.9-build00167.min.js" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery-1.10.2.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="respond.js" />
